sudo: required
services:
  - docker

before_install:
  - docker build -t saathwik2414/docker-react -f Dockerfile.dev .

script:
  - docker run saathwik2414/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-595989425776"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY